### ISSUE TITLE
Unexpected `Cleanup` call when an outer `Establish` throws

### ISSUE THREAD

**Issue by ulrichb** [machine/machine.specifications#183]
Given this spec...

``` C#
    [Subject("some subject")]
    class SpecWithThrowingEstablish
    {
        Establish context = () =>
        {
            throw new Exception();
        };

        Cleanup cleanup = () =>
        {
            Console.WriteLine("outer cleanup");
        };

        class WhenDoingSomething
        {
            Because of = () => { };

            It happend_something = () => { };

            Cleanup cleanup = () =>
            {
                Console.WriteLine("inner cleanup");
            };
        }
    }
```

... then after the outer `Establish` throws, the outer `Cleanup` will be called, which is OK, because the corresponding `Establish`had been (partly) executed.

But the inner `Cleanup` will be executed too, which is a bug to my eyes, because the corresponding inner `Establish` never executed.

**Comment by drauch** [comment]
Reopened the issue as it is still a problem. Of course, the corresponding cleanup should run if the Establish throws, however, NOT cleanups which correspond to Establish clauses which have not been run (e.g. in derived or nested classes).

See also other test runners (e.g. NUnit).

**Comment by DerAlbertCom** [comment]
@drauch how to cleanup a partially established context? IMHO Cleanup should be called, and check if the resource to clean are initiated

**Comment by drauch** [comment]
If there is a base-class Establish and a derived-class Establish, and the base-class Establish already throws an exception, then the base-class Cleanup should be called but not the derived-class Cleanup. This is the case in all test frameworks I know, only MSpec does it differently...which is confusing :)

**Comment by BrunoJuchli** [comment]
I agree with drauch.

**Comment by NameOfTheDragon** [comment]
I can see arguments both ways on this one, but the main principle seems to be that if a test can’t complete its Establish phase then that is a bug in the test and it needs to be fixed. Whatever happens after that point is going to be risky in some situations because there’s no way of knowing what state anything is in.

Without any clear use case for changing the behaviour (a breaking change), then I think I would support Daniel’s original decision to maintain the status quo, which he says is ‘by design’.

Is the current behaviour causing some specific problem?

Regards,
Tim Long

**Comment by BrunoJuchli** [comment]
Hm i guess it was quite late yesterday and i didn't give it enough thought.
When establish/cleanup fails it's important that the user is informed that this happened (so he can fix establish/cleanup). The rest of the test-run is then not necessarily realiable, so it might actually be the best course of action to abort the test-run *immediately* to clearly indicate an important problem which needs to be fixed ASAP (instead of giving the impression of a single failed test - remember TDD workflow and that all subsequent tests might be false positives).

Image the following:

    private static ManualResetEventSlim twoResource;

    Establish context = () => {
        twoResource = null;        
        One();
        twoResource = Two();
        Three();
    };

    Cleanup after = () => {
         CleanupOne();
         twoResource.Dispose();
         twoResource = null;
         CleanupThree();
    };

Now let's say `Two()` throws and we execute cleanup.  Subsequently `Cleanup` throws a `NullReferenceException` at `twoResource.Dispose()`. So do we need to report two exceptions or one? We certainly must report the `Establish` one because it's the root cause. But should we report the `Cleanup` one, too?

Now, if the user actually needs `Cleanup` to be run he's still got to adapt his code so it runs reliably:

     private static bool establishOneSuccessful;
     private static bool establishThreeSuccessful;

    Establish context = () => {
        twoResource = null;        
        One();
        establishOneSuccessful = true;
        twoResource = Two();
        Three();
        establishThreeSuccesful = true;
    };

    Cleanup after = () => {
         if(establishOneSuccessful)
         {
             CleanupOne();
         }
         if(twoResource != null)
         {
             twoResource.Dispose();
             twoResource = null;
         }
         if(establishThreeSuccessful)
         {
             CleanupThree();
         }
    };

And I for one am clearly not expecting users to write tons of boiler-plate code like that, especially since I perceive the benefit as minimal (being able to complete a test run).
So should there any change be done i vote for immediate abortion of test run with proper reporting of the offending exception.

**Comment by drauch** [comment]
@BrunoJuchli : Please note, that your example has nothing to do with the issue at hand. I'm in favor of executing the corresponding Cleanup even if the Establish failed - just not if the Establish has never been run (i.e., an Establish in a base or outer class has already failed)!

**Comment by BrunoJuchli** [comment]
@drauch 
That's exactly what i'm talking about. The case where `Establish` fails somewhere in between (here `Two()`) and then the corresponding `Cleanup` (which needs to clean-up `twoResource` is executed.)

**Comment by BrunoJuchli** [comment]
sorry i hit the `Close` by accident.

**Comment by drauch** [comment]
@BrunoJuchli : No, there is a different between "One Establish block has exited somewhere in the middle of execution" and "One Establish block has never ever been even started, because a previous Establish block has not finished".

**Comment by BrunoJuchli** [comment]
@drauch 
My example is about "One Establish block has exited somewhere in the middle of execution" . My example doesn't even consider inherited Establish's and Cleanup's and i don't know where our misunderstanding is supposed to be.
There is only one `Establish` and `Cleanup` clause in my example code, each.

**Comment by NameOfTheDragon** [comment]
So far there are three extant opinions about how this should work, all of which are perfectly valid in my opinion:

1.       fail immediately, don’t run any cleanup

2.       run all cleanups then fail (the current by-design behaviour)

3.       run only clean-ups for which the matching Establish has at least partially executed, then fail.

To be clear, if your Establish fails, that is a bug in the test. If you are going to be writing tests with that much complexity that your Establish can throw an unhandled exception, then I think the onus is on you to make sure your cleanups can cope with that situation.

You say that Cleanup should not run if the corresponding Establish has not run – but what if there are static initializers that need to be cleaned up?

Unless you can make a strong use-case for making a breaking change to the existing by-design behaviour, then I think it should be left as-is.

Regards,
Tim Long
