### ISSUE TITLE
Rider/R# 2020.2 support

### ISSUE THREAD

**Issue by dp0h** [machine/machine.specifications#412]
Plugint is not working in the latest Rider/R# version.

**Comment by robertcoltheart** [comment]
This is being worked on, there are significant breaking changes, as JB have re-written all the unit test code. It may take a few days to get this out. I'd suggest rolling back your upgrades for now.

**Comment by dp0h** [comment]
Thanks for the update. I'll use previous version for a while.

**Comment by iSchlicht** [comment]
+1

**Comment by robertcoltheart** [comment]
Work is finished on this, I'm now testing and fixing bugs. Hoping to have a final release pushed out in the next 2-3 days.

**Comment by robertcoltheart** [comment]
The plugin update has been pushed to JetBrains plugins, it will take 2-3 business days for them to approve and for it to appear in the extension manager.

**Comment by robertcoltheart** [comment]
This update has been approved by Jetbrains and is now available in the extensions manager.

**Comment by tpeplow** [comment]
Just an FYI on this.  I'm not sure of the root cause, I _think_ it's because I don't run Rider elevated, but after I installed the plugin I was unable to run tests. It complained it couldn't find the test runner in this location `C:\Program Files\JetBrains\JetBrains Rider 2020.1.4\lib\ReSharperHost\TestRunner\Adapters`

To resolve it I found where the plugin was installed and there was the adapters I needed in there (which was `%localappdata%\JetBrains\Rider2020.2\resharper-host\local\Shared\vAny\DeployedPackagesExpand\Machine.Specifications.Runner.Resharper9.2020.2.1~081F617F0B\TestRunner\Adapters`

I copied the MSpec folder into `C:\Program Files\JetBrains\JetBrains Rider 2020.1.4\lib\ReSharperHost\TestRunner\Adapters` folder and the tests run.

Not sure where the _bug_ is, I didn't check if my running elevated assumption, but if you get an error not being able to find `Machine.Specifications.Runner.ReSharper.Adapters.net40` then this should do it.

**Comment by robertcoltheart** [comment]
Interesting, I'll debug further and see what the issue is.

**Comment by robertcoltheart** [comment]
Fix is here (I think): https://github.com/machine/machine.specifications.runner.resharper/pull/139

**Comment by robertcoltheart** [comment]
This has been released to JetBrains marketplace. Unfortunately it will take another 2 days for JB to approve it 🤷. If you want to side-step this, download the binaries and install them manually from here: https://github.com/machine/machine.specifications.runner.resharper/releases/tag/v2020.2.2

**Comment by andhuman** [comment]
I still have issues using the latest 2020.2.2.

Message = “
  TestRunner: Application  JetBrains.Rd.Tasks.RdFault: Could not load file or assembly 'file:///C:\Users\andhuman\AppData\Local\JetBrains\Rider2020.2\resharper-host\local\Shared\vAny\DeployedPackagesExpand\Machine.Specifications.Runner.Resharper9.2020.2.2~2DDA28307D\TestRunner\Adapters\MSpec\net40\Machine.Specifications.Runner.ReSharper.Adapters.Tasks.net40.dll' or one of its dependencies. The system cannot find the file specified., reason: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\andhuman\AppData\Local\JetBrains\Rider2020.2\resharper-host\local\Shared\vAny\DeployedPackagesExpand\Machine.Specifications.Runner.Resharper9.2020.2.2~2DDA28307D\TestRunner\Adapters\MSpec\net40\Machine.Specifications.Runner.ReSharper.Adapters.Tasks.net40.dll' or one of its dependencies. The system cannot find the file specified.
  File name: 'file:///C:\Users\andhuman\AppData\Local\JetBrains\Rider2020.2\resharper-host\local\Shared\vAny\DeployedPackagesExpand\Machine.Specifications.Runner.Resharper9.2020.2.2~2DDA28307D\TestRunner\Adapters\MSpec\net40\Machine.Specifications.Runner.ReSharper.Adapters.Tasks.net40.dll'

The file exist in the location so I don't know why it is complaining.

**Comment by robertcoltheart** [comment]
I can reproduce, I'll dive back in... 😓

**Comment by robertcoltheart** [comment]
_sigh_ It seems as though it's a path that is longer than 260 characters, and Rider nests the file so deeply that it is overrunning this limit which exists in .NET versions prior to `net462`. Net Core seems to be unaffected. I'll get out a fix shortly.

**Comment by robertcoltheart** [comment]
Fixed here and released: https://github.com/machine/machine.specifications.runner.resharper/pull/142 It will take 2-3 days to be approved by JB. 

If you want it earlier, please set up a Nuget feed here (for ReSharper): https://github.com/machine/machine.specifications.runner.resharper/packages

Or for Rider, download the ZIP and install manually here: https://github.com/machine/machine.specifications.runner.resharper/releases/tag/v2020.2.3
